using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace HTags.Editor
{
    public static class HTagCodeGenerator
    {
        // Keep this in sync with "Packages/com.edwardbrave.htags/package.json".
        private const string Version = "0.5.0";
        
        private const int SpacesPerIndentLevel = 4;

        private static (string, string) _hTagSoTemplate = new ("HTagSoTemplate", "{0}So.cs");
        private static (string, string) _hTagEventBusTemplate = new ("HTagEventBusAssetTemplate", "{0}EventBusAsset.cs");
        private static (string, string) _hTagEventBusDispatcherTemplate = new ("HTagEventBusDispatcherTemplate", "{0}EventBusDispatcher.cs");
        
        
        
        private static readonly StringBuilder TempBuilder = new ();
        
        // Updates the given file with wrapper code generated for the given action sets.
        // If the generated code is unchanged, does not touch the file.
        // Returns true if the file was touched, false otherwise.
        public static void GenerateWrapperCode(HTagAsset asset, HTagAsset.Options options, List<string> tagNames)
        {
            options.namespaceName = CSharpCodeHelpers.MakeNamespaceName(options.namespaceName);
            options.tagName = CSharpCodeHelpers.MakeTypeName(Path.GetFileNameWithoutExtension(string.IsNullOrWhiteSpace(options.tagName) ? asset.name : options.tagName));

            if (string.IsNullOrWhiteSpace(options.tagFilesFolderPath))
            {
                options.tagFilesFolderPath = Path.GetDirectoryName(AssetDatabase.GetAssetPath(asset));
            }

            var validatedTags = CSharpCodeHelpers.GetValidatedListOfTagNames(tagNames);

            Directory.CreateDirectory(options.tagFilesFolderPath);
            
            var templateFilePairs = new List<(string, string)> (2) { _hTagSoTemplate };
            if (options.generateEventBus)
            {
                templateFilePairs.Add(_hTagEventBusTemplate);
                templateFilePairs.Add(_hTagEventBusDispatcherTemplate);
            }
            
            foreach (var (templateName, fileName) in templateFilePairs)
            {
                string combinedPath = Path.Combine(options.tagFilesFolderPath, string.Format(fileName, options.tagName));
                string code = InternalGenerateWrapperCode(templateName, asset.name, options, validatedTags);
                
                if (File.Exists(combinedPath))
                {
                    string existingCode = File.ReadAllText(combinedPath);
                    if (existingCode == code || existingCode.WithAllWhitespaceStripped() == code.WithAllWhitespaceStripped())
                    {
                        continue;
                    }
                }
                
                CSharpCodeHelpers.CheckOut(combinedPath);
                File.WriteAllText(combinedPath, code);
            }

            AssetDatabase.Refresh();
        }

        private static string InternalGenerateWrapperCode(string templateAssetPath, string assetName, HTagAsset.Options options, List<string> validatedTags)
        {
            int indentLevel = 0;
            Action lateCommand = null;
            
            bool isNamespaceDeclared = !string.IsNullOrEmpty(options.namespaceName);
            var templateAsset = Resources.Load<TextAsset>(templateAssetPath);
            var templateAssetLines = templateAsset.text.Split(new[] { "\r\n", "\n", "\r" }, StringSplitOptions.None);
            
            StringBuilder builder = new StringBuilder();
            builder.Append(CSharpCodeHelpers.MakeAutoGeneratedCodeHeader(nameof(HTagCodeGenerator), Version, assetName));

            foreach (var line in templateAssetLines)
            {
                var matches = Regex.Matches(line, @"\$[^""].*?\$");
                
                if (matches.Count == 0)
                {
                    WriteIndent(builder);
                    builder.AppendLine(line);
                    continue;
                }
                
                string nextLine = line;
                foreach (Capture match in matches)
                {
                    var command = CodeGenCommand.TryRead(match);
                    if (!command.IsValid)
                    {
                        throw new ArgumentException($"Invalid command: {match.Value}");
                    }

                    PerformCommand(command, ref nextLine);
                }
                
                WriteIndent(builder);
                lateCommand?.Invoke();
                lateCommand = null;
                builder.AppendLine(nextLine);
            }
            
            return builder.ToString();
            

            void PerformCommand(CodeGenCommand command, ref string line)
            {
                switch (command.Name)
                {
                    case "BeginNamespace":
                        if (isNamespaceDeclared)
                        {
                            line = command.ReplaceWith(line, $"namespace {options.namespaceName} \n{{");
                            lateCommand += () => indentLevel++;
                        }
                        else
                        {
                            line = command.ReplaceWith(line, "");
                        }

                        break;
                    case "EndNamespace":
                        if (isNamespaceDeclared)
                        {
                            line = command.ReplaceWith(line, "}");
                            indentLevel--;
                        }
                        else
                        {
                            line = command.ReplaceWith(line, "");
                        }

                        break;
                    case "FileName":
                        line = command.ReplaceWith(line, options.tagName);
                        
                        break;
                    case "TagsCount":
                        line = command.ReplaceWith(line, validatedTags.Count.ToString());
                        
                        break;
                    case "PopulateTagsInline":
                    {
                        var tagNames = validatedTags.Select(tag => tag.Replace('.', '_'));
                        line = command.ReplaceWith(line, TempBuilder.AppendJoin(',', tagNames).ToString());
                        TempBuilder.Clear();
                    } break;
                    case "PopulateTagsNamesInline":
                    {
                        for (int i = 0; i < validatedTags.Count; ++i)
                        {
                            TempBuilder.Append('"');
                            TempBuilder.Append(validatedTags[i]);
                            TempBuilder.Append('"');
                            if (i < validatedTags.Count - 1)
                            {
                                TempBuilder.Append(',');
                            }
                        }
                        
                        line = command.ReplaceWith(line, TempBuilder.ToString());
                        TempBuilder.Clear();
                    } break;
                    case "PopulateRegisteredTags":
                    {
                        StringBuilder indexesBuilder = new StringBuilder();
                        string tempLine = command.ReplaceWith(line, command.Body);
                        
                        for (int i = 0; i < validatedTags.Count; i++)
                        {
                            indexesBuilder.Clear();
                            indexesBuilder.AppendJoin(',', CSharpCodeHelpers.GetTagHierarchyIDs(validatedTags[i], validatedTags));
                            
                            if (i != 0) WriteIndent(TempBuilder);
                            TempBuilder.AppendFormat(tempLine, options.tagName, validatedTags[i].Replace('.', '_'), indexesBuilder);
                            if (i != validatedTags.Count - 1) TempBuilder.AppendLine();
                        }

                        line = TempBuilder.ToString();
                        TempBuilder.Clear();
                    } break;
                    default:
                        throw new ArgumentException($"Unknown command: {command.Name}");
                }
            }
            
            void WriteIndent(StringBuilder strBuilder)
            {
                for (var i = 0; i < indentLevel; ++i)
                {
                    for (var n = 0; n < SpacesPerIndentLevel; ++n)
                        strBuilder.Append(' ');
                }
            }
        }
    }
}
